-- auto Generated on 2019-06-14
-- DROP TABLE IF EXISTS aa;
CREATE TABLE aa(
	id VARCHAR (50) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'aa';
